# See also: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "-"
    groups:
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "*"
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    pull-request-branch-name:
      separator: "-"
