name: Publish release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npmjs-publishing
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - uses: ./.github/actions/build

      - name: Calculate release name
        id: release-name
        run: |
          echo "release_version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Publish npm package
        run: |
          npm version --no-git-tag-version "${{ steps.release-name.outputs.release_version }}"
          npm publish --provenance
