name: Publish release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npmjs-publishing
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - uses: ./.github/actions/build

      - name: Calculate release name
        id: release-name
        run: |
          echo "release_version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Publish npm package
        run: |
          npm version --no-git-tag-version "${{ steps.release-name.outputs.release_version }}"
          npm publish --provenance
